# Generated by Django 5.0.2 on 2024-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tags_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'tag'},
        ),
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
