# Generated by Django 5.0.2 on 2024-02-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
